CREATE TABLE productos (
id INT NOT NULL AUTO_INCREMENT,	
imagen VARCHAR(100) NULL,
nombre VARCHAR(50) NULL,
descripcion VARCHAR(100) NULL,
precio VARCHAR(10) NULL,
stock VARCHAR(10) NULL,
fecha DATE NULL,
PRIMARY KEY(id)
);
